### PR TITLE
ISSUE-311 support multivariable rasters

### PR DESCRIPTION
**Pull request by gwlucastrig**
This PR may not be quite ready for review.  I still have to write Junit tests for the new methods.  So the overall coverage will be decreased until I do so.

### CODE REVIEW

**Comment by gwlucastrig** [comment]
I've fixed most of the whitespace-related issues.  So I hope the code will be easier to review.

Unfortunately, some of the Javadoc received different line-breaks, and I don't think I will be able to restore them without an undue amount of effort.

Otherwise, the code is now ready for review.

**Comment by kinow** [comment]
>I've fixed most of the whitespace-related issues. So I hope the code will be easier to review.
>Unfortunately, some of the Javadoc received different line-breaks, and I don't think I will be able to restore them without an undue amount of effort.

Thanks and not a problem @gwlucastrig !

>Otherwise, the code is now ready for review.

:+1: hopefully will be complete by end of week. Thanks for the PR !

**Comment by gwlucastrig** [comment]
It was going well, but it may have fallen apart at the end.  When I did a git rebase with a squash, git pulled in some merge commits with recent dependabot changes.    Some of the commit comments for things I didn't work on (like pom.xml) may have been modified.

If necessary, I can scuttle this PR and resubmit it.

**Comment by gwlucastrig** [comment]
It will be easy enough to cancel the PR and submit a new one with my
changes. I will not make any additional code changes so the review should
be straightforward.

**Comment by gwlucastrig** [comment]
This PR is now obsolete.

**Pull request closed without merging**
