### PR TITLE
Need *.webp type images reader and writer

### PR DESCRIPTION
**Pull request by changbaishan**
As more and more *.webp type images popping up everywhere, I hope commons imaging will help us to read and write this type of images.

As an example, https://i.guancha.cn/bbs/2019/07/10/20190710110612113 is pretty exciting.

Thanks very much!

### CODE REVIEW

**Comment by kinow** [comment]
Sounds like a good idea. I think there was some merge/rebase issue somewhere. There are way too many commits in this PR. You may want to review your commit log, rebase onto master, and make sure there are fewer changes in the PR, as that makes it easier to be reviewed/merged.

Thanks!

**Comment by kinow** [comment]
Commits still needing to be squashed. Right now in GitHub UI it shows 59 commits in this PR.

**Comment by kinow** [comment]
Hmmm, we can't really merge the PR until it is properly rebased. Where it is now saying in GitHub that "changbaishan wants to merge 120 commits into..." it should actually say something like "changbaishan wants to merge 1 commits into", because normally PR's contain just a few commits. I don't think these 120 commits are related to webp type images.

@changbaishan could you look into it, please? Happy to review once that's sorted.

**Comment by changbaishan** [comment]
Is there way I can release myself from this PR? I witnessed wonderful works you did. However, I opened it just to suggest a useful feature. I had no idea of what it actually meant. I still love your software. Just don't want to prolong a mistake.

**Comment by kinow** [comment]
> Is there way I can release myself from this PR? I witnessed wonderful works you did. However, I opened it just to suggest a useful feature. I had no idea of what it actually meant. I still love your software. Just don't want to prolong a mistake.

Your action got the right reaction then :-) we definitely need a webp parser, and I will create a JIRA issue for that. And it was no mistake at all. Feel free to raise issues, pull requests, etc, for whatever new ideas or bugs you may have.

Cheers
Bruno

**Comment by kinow** [comment]
FYI https://issues.apache.org/jira/browse/IMAGING-57

**Comment by changbaishan** [comment]
Thanks very much! I really appreciate you and your work. Just that I don't know enough to handle the work. Sorry again. Looking forward to use your new release.

**Pull request closed without merging**
