### PR TITLE
[IMAGING-342] Read PNG metadata from iTXt chunk

### PR DESCRIPTION
**Pull request by Glavo**
In [PNG specification](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html#C.Anc-text), `iTXt` chunk is semantically equivalent to the `tEXt` and `zTXt` chunks, but `PngImageParser::getMetadata` does not recognize the `iTXt` chunk.

This PR fixes this problem.

### CODE REVIEW

**Review by kinow — COMMENTED** [review]
:+1: small change, but do you think we could have a unit test for this (to make sure we don't accidentally drop this from the parser again).

We also need a JIRA to add it to the changelog. Can you create one, please, @Glavo ?

Thanks!

**Comment by kinow** [comment]
I also realized it's hard to know what version of each spec we support, so here's a new one for 1.0 - https://issues.apache.org/jira/browse/IMAGING-341

**Comment by Glavo** [comment]
I added a test to check whether the metadata with Unicode characters can be correctly obtained from PNG images.

**Review by kinow — APPROVED** [review]
Confirmed the test was using that chunk type.

image

CI happy, looks good to me! I will squash the commits into a single one prefixed by the [IMAGING-...] issue ID, and then merge it later.

Thanks @Glavo !

**Comment by kinow** [comment]
Merged!

**Pull request closed without merging**
