### PR TITLE
Replace explicit type with <>.

### PR DESCRIPTION
**Pull request by arturobernalg**

### CODE REVIEW

**Comment by kinow** [comment]
@arturobernalg thanks a lot for the PR! Do you mind if I merge #116 first, and then we see what's left after that change? I guess some of the changes may have been fixed, and I also don't want to touch that PR again after the final review :sweat_smile: 

Thank you!
Bruno

**Comment by arturobernalg** [comment]
> @arturobernalg thanks a lot for the PR! Do you mind if I merge #116 first, and then we see what's left after that change? I guess some of the changes may have been fixed, and I also don't want to touch that PR again after the final review 😅
> 
> Thank you! Bruno

HI @kinow 
Sure.
TY

**Comment by kinow** [comment]
That PR has been merged. Can you rebase and take a look if your PR needs to be updated, please, @arturobernalg . Thanks!

**Comment by arturobernalg** [comment]
> That PR has been merged. Can you rebase and take a look if your PR needs to be updated, please, @arturobernalg . Thanks!

Hi @kinow 
Done.
TY

**Review by kinow — APPROVED** [review]
Brilliant! Thanks @arturobernalg ! Just waiting on CI.

**Pull request merged**
