### PR TITLE
IMAGING-176

### PR DESCRIPTION
**Pull request by GabiAxel**
When "Compression" field is missing in TIFF - default to no compression to avoid exception.

### CODE REVIEW

**Comment by britter** [comment]
Is the compression field optional in TIFF files or does the absence of the compression field indicate a broken file?

**Comment by GabiAxel** [comment]
I'm not an expert on this, but according to https://en.wikipedia.org/wiki/Tagged_Image_File_Format#TIFF_Compression_Tag "The default value is 1 = no compression", which seems to me that the field is optional.

I got several such files from a user of my app, and they can be opened with different programs just fine, but cause an exception when attempting to get their info with Commons Imaging.

**Comment by britter** [comment]
@GabiAxel okay! Do you see a way to provide a unit test for the new behavior?

**Comment by GabiAxel** [comment]
I'll try to work on this in the next few days.

**Comment by britter** [comment]
Awesome! Thank you.

**Comment by GabiAxel** [comment]
@britter I pushed another change and a test TIFF file which caused failure in TiffReadTest and the change makes the test pass.

**Comment by britter** [comment]
@GabiAxel I'll have a look tomorrow!

**Comment by GabiAxel** [comment]
@britter `TiffReadTest` does that - it loads all TIFF images, and by adding the new image `src/test/data/images/tiff/8/no-compression-tag.tiff` this test runs `Imaging.getMetadata()` for it too. I didn't add new behaviour, just fixed how `Imaging.getMetadata()` deals with a case of an image, so I think it's enough.

**Comment by britter** [comment]
Fixed in SVN in revision 1749362. Should sync to GitHub shortly. Thank you!

**Pull request closed without merging**
