### PR TITLE
IMAGING-130: Ignore extra bytes when LZW decoder table is full

### PR DESCRIPTION
**Pull request by mgs255**
Per the helpful comments from @DhyanB it would appear that the correct fix in this case is to simply ignore extra bytes during GIF decoding.  Added an animated GIF that was previously causing an IOException.

### CODE REVIEW

**Comment by mgs255** [comment]
Build failure due to [ERROR] 7002: org.apache.commons.imaging.common.bytesource.ByteSource: Method 'public java.lang.String getFilename()' has been removed, addressed by #45

**Comment by kinow** [comment]
Hi @mgs255 

Thanks for your contribution, for using the JIRA issue, and even including a test file!

The issue with the Travis build has been fixed in master. Could you please rebase your work? It should be built by Travis and hopefully pass now.

Cheers

**Comment by kinow** [comment]
Tests passing, coverage looks good. I just need to read the issue with calm and review the change. Hoping to have time tomorrow. If no problems found, should be merged before the weekend. Thanks @mgs255 !

**Comment by mgs255** [comment]
Great stuff, thanks @kinow ! Good luck getting to a 1.0 release.

**Comment by kinow** [comment]
Merged, will be released with 1.0-alpha2.

>Good luck getting to a 1.0 release.

Thanks, what we need to progress towards 1.0 is exactly this. Users trying the current API, addressing mainly bugs (though we may be able to change some of the API as well if necessary) and providing useful feedback.

Thanks a lot @mgs255 !
Bruno

**Pull request merged**
